// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk9HHX8LaThfT6Q12QNO78p7cEj3425RA',
    appId: '1:694167397444:web:7e0fde130ddf29deb6c811',
    messagingSenderId: '694167397444',
    projectId: 'vello-dac50',
    authDomain: 'vello-dac50.firebaseapp.com',
    storageBucket: 'vello-dac50.firebasestorage.app',
    measurementId: 'G-368YG587BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-fVWOzdLDXbxuTO38GRMV4TYCo9-vVR4',
    appId: '1:694167397444:android:15fcb59ff06f7042b6c811',
    messagingSenderId: '694167397444',
    projectId: 'vello-dac50',
    storageBucket: 'vello-dac50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdofdFr9w0jxZeCUTyrsFpIfzNVQcKOtA',
    appId: '1:694167397444:ios:81a35e7a485ea668b6c811',
    messagingSenderId: '694167397444',
    projectId: 'vello-dac50',
    storageBucket: 'vello-dac50.firebasestorage.app',
    iosBundleId: 'com.vello.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdofdFr9w0jxZeCUTyrsFpIfzNVQcKOtA',
    appId: '1:694167397444:ios:81a35e7a485ea668b6c811',
    messagingSenderId: '694167397444',
    projectId: 'vello-dac50',
    storageBucket: 'vello-dac50.firebasestorage.app',
    iosBundleId: 'com.vello.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk9HHX8LaThfT6Q12QNO78p7cEj3425RA',
    appId: '1:694167397444:web:3e9c86d0d4a6b86cb6c811',
    messagingSenderId: '694167397444',
    projectId: 'vello-dac50',
    authDomain: 'vello-dac50.firebaseapp.com',
    storageBucket: 'vello-dac50.firebasestorage.app',
    measurementId: 'G-15ESNH6Q00',
  );
}
