name: vello
description: Vello Passageiro

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  url_launcher: ^6.2.6
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.5
  firebase_auth: ^4.15.3
  firebase_storage: ^11.6.6
  image_picker: ^1.1.0
  http: ^1.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/


