export type Corrida = {
  passageiroId: string;
  passageiroNome: string;
  passageiroTelefone: string;
  passageiroFoto?: string;
  motoristaId?: string;
  motoristaNome?: string;
  motoristaTelefone?: string;
  motoristaFoto?: string;
  placaVeiculo?: string;
  modeloVeiculo?: string;
  corVeiculo?: string;
  origem: { endereco: string; latitude: number; longitude: number; complemento?: string };
  destino: { endereco: string; latitude: number; longitude: number; complemento?: string };
  paradasAdicionais?: { endereco: string; latitude: number; longitude: number; ordem: number; concluida: boolean }[];
  valor: number;
  valorMotorista: number;
  taxaPlataforma: number;
  formaPagamento: 'cartao'|'dinheiro'|'pix';
  cupomDesconto?: string; valorDesconto?: number;
  status: 'pendente'|'aceita'|'motorista_a_caminho'|'motorista_chegou'|'em_andamento'|'concluida'|'cancelada_passageiro'|'cancelada_motorista';
  dataHoraSolicitacao: FirebaseFirestore.Timestamp;
  dataHoraAceita?: FirebaseFirestore.Timestamp;
  dataHoraMotoristaACaminho?: FirebaseFirestore.Timestamp;
  dataHoraMotoristaChegou?: FirebaseFirestore.Timestamp;
  dataHoraInicio?: FirebaseFirestore.Timestamp;
  dataHoraConclusao?: FirebaseFirestore.Timestamp;
  dataHoraCancelamento?: FirebaseFirestore.Timestamp;
  motivoCancelamento?: string;
  corridaCompartilhada?: boolean; maxPassageiros?: number; passageirosAtuais?: number;
  avaliacaoPassageiro?: number; avaliacaoMotorista?: number;
  comentarioPassageiro?: string; comentarioMotorista?: string;
  distanciaEstimada: number; distanciaPercorrida?: number; tempoEstimado: number; tempoViagem?: number;
  emergencia?: boolean; compartilhadaCom?: string[];
  criadoEm: FirebaseFirestore.Timestamp; atualizadoEm: FirebaseFirestore.Timestamp;
};
