// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7WjUAAKtOxryMD-1luUPjIm9AstqFw7E',
    appId: '1:448618578101:web:0b650370bb29e29cdd0b6f',
    messagingSenderId: '448618578101',
    projectId: 'vello-passageiro-premium',
    authDomain: 'vello-passageiro-premium.firebaseapp.com',
    storageBucket: 'vello-passageiro-premium.appspot.com',
    measurementId: 'G-PBXCXCYXMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASHy2gUBUh8_72dJrMn9lJrdN-c9B8hAo',
    appId: '1:448618578101:android:f4424967dd0b6fd1dd0b6f',
    messagingSenderId: '448618578101',
    projectId: 'vello-passageiro-premium',
    storageBucket: 'vello-passageiro-premium.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBssGKbyOIk_NinNtCQ84PJ2mrmDfrBBhQ',
    appId: '1:448618578101:ios:f4424967dd0b6fd1dd0b6f',
    messagingSenderId: '448618578101',
    projectId: 'vello-passageiro-premium',
    storageBucket: 'vello-passageiro-premium.appspot.com',
    iosBundleId: 'com.vello.passageiro.premium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBssGKbyOIk_NinNtCQ84PJ2mrmDfrBBhQ',
    appId: '1:448618578101:macos:f4424967dd0b6fd1dd0b6f',
    messagingSenderId: '448618578101',
    projectId: 'vello-passageiro-premium',
    storageBucket: 'vello-passageiro-premium.appspot.com',
    iosBundleId: 'com.vello.passageiro.premium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASHy2gUBUh8_72dJrMn9lJrdN-c9B8hAo',
    appId: '1:448618578101:windows:f4424967dd0b6fd1dd0b6f',
    messagingSenderId: '448618578101',
    projectId: 'vello-passageiro-premium',
    storageBucket: 'vello-passageiro-premium.appspot.com',
  );
}